Seminario de Ing Soft/Proyecto/Codigo/app/products/models.py
from datetime import datetime
from sqlalchemy.sql.expression import func
# from flask import jsonify

from app.db import db, ma
from app.products.exceptions import ProductNotFoundError


class Product(db.Model):
    """
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    image = db.Column(db.String(500), default="https://bit.ly/3loPYXP")
    price = db.Column(db.Integer, nullable=False)
    weight = db.Column(db.Integer, default=1)
    description = db.Column(db.String(500), nullable=True)
    # long_description = db.Column(db.String(10000), nullable=True)
    refundable = db.Column(db.Boolean, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    created_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, default=datetime.now())


class ProductSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Product
        fields = ["id", "name", "price", "description", "image", "refundable",
                  "weight", "refundable"]


class Category(db.Model):
    """
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    image = db.Column(db.String(500), default="https://bit.ly/3loPYXP")
    created_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, default=datetime.now())


class CategorySchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Category
        fields = ["id", "name", "image"]


class Stock(db.Model):
    """
    """
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'))
    quantity = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now())
    updated_at = db.Column(db.DateTime, default=datetime.now())


def get_all_categories():
    categories = Category.query.all()
    category_schema = CategorySchema()
    categories = [category_schema.dump(category) for category in categories]
    return categories


def create_new_category(name):
    category = Category(name=name)
    db.session.add(category)

    if db.session.commit():
        return category

    return category


def create_new_product(name, price, weight, description, refundable,
                       category_name, image):

    if refundable == 1:
        refundable = True
    else:
        refundable = False

    category = Category.query.filter_by(name=category_name).first()

    category_id = category.id

    product = Product(name=name, price=price, weight=weight,
                      description=description, refundable=refundable,
                      category_id=category_id, image=image)
    db.session.add(product)
    if db.session.commit():
        return product

    return product


def get_all_products():
    products_qs = Product.query.all()
    product_schema = ProductSchema()
    products_serialization = [product_schema.dump(product) for product in
                              products_qs]

    return products_serialization


def get_product_by_id(id):
    product_qs = Product.query.filter_by(id=id).first()
    if product_qs:
        product_schema = ProductSchema()
        p = product_schema.dump(product_qs)
        return p
    else:
        raise ProductNotFoundError


def get_category_by_id(id):
    category_qs = Category.query.filter_by(id=id).first()
    if category_qs:
        category_schema = CategorySchema()
        c = category_schema.dump(category_qs)
        return c
    else:
        raise ProductNotFoundError


def get_category_products_by_id(category_id):
    products_qs = Product.query.filter_by(category_id=category_id).all()
    product_schema = ProductSchema()
    products_serialization = [product_schema.dump(product) for product in
                              products_qs]
    return products_serialization


def add_stock(product_id, quantity):
    stock = Stock.query.filter_by(product_id=product_id).first()
    if stock is None:
        stock = Stock(product_id=product_id, quantity=quantity)
        db.session.add(stock)
        if db.session.commit():
            return stock
    else:
        stock = Stock.query.filter_by(product_id=product_id).update(
            {"quantity": Stock.quantity + quantity})
        if db.session.commit():
            return stock

    return None


def get_last_products():
    last = Product.query.order_by(Product.id.desc()).limit(4).all()
    return last


def get_random_categories():
    random_categories = Category.query.order_by(func.random()).limit(4)
    return random_categories


def get_order_products(order_items):
    '''
    Obtiene los productos de una orden a partir de los items que esta tiene
    '''
    products = []
    for product in order_items:
        products.append(Product.query.filter_by(id=product.product_id).first())

    return products


def get_product_stock(product):
    '''
    Obtiene el stock de un producto
    '''
    stock = Stock.query.filter_by(product_id=product.id).first()

    return stock.quantity

    # ARREGLAR PRODIC ID DE ORDER_ITEM ESTA MAL, VER ORDER EN EL CARRITO

Seminario de Ing Soft/Proyecto/Codigo/app/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class CreateCategoryForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])


class CreateProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    price = StringField('Price', validators=[DataRequired()])
    weight = StringField('Weight', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    refundable = StringField('Refundable [1|0]', validators=[DataRequired()])
    category_id = StringField('Category ID', validators=[DataRequired()])
    image = StringField('image', validators=[DataRequired()])

Seminario de Ing Soft/Proyecto/Codigo/app/products/__init__.py
DEBUG = True  # Turns on debugging features in Flask

Seminario de Ing Soft/Proyecto/Codigo/app/products/views.py
from http import HTTPStatus
from flask import Blueprint, Response, request, render_template, redirect, \
    url_for, flash
from app.products.forms import (
    CreateCategoryForm,
    CreateProductForm
)
from app.products.models import (
    get_all_categories,
    create_new_category,
    get_all_products,
    get_product_by_id,
    get_category_products_by_id,
    create_new_product,
    add_stock
)

from app.order.models import (
    get_active_order,
    create_order,
    add_item_order
)

from flask_login import login_required, current_user

products = Blueprint("products", __name__, url_prefix='/products')

EMPTY_SHELVE_TEXT = "Empty shelve!"
PRODUCTS_TITLE = "<h1> Products </h1>"
DUMMY_TEXT = "Dummy method to show how Response works"
RESPONSE_BODY = {
    "message": "",
    "data": [],
    "errors": [],
    "metadata": []
}


@products.route('/dummy-product', methods=['GET', 'POST'])
@login_required
def dummy_product():
    """ This method test the request types. If is GET Type it will
    render the text Products in h1 label with code 500.
    If is POST Type it will return Empty shelve! with status code 403
    """
    if request.method == 'POST':
        return EMPTY_SHELVE_TEXT, HTTPStatus.FORBIDDEN

    return PRODUCTS_TITLE, HTTPStatus.INTERNAL_SERVER_ERROR


@products.route('/dummy-product-2')
@login_required
def dummy_product_two():
    """ This method shows how Response object could be used to make API
    methods.
    """
    return Response(DUMMY_TEXT, status=HTTPStatus.OK)


@products.route('/categories')
def get_categories():
    """
        Verificar que si get_all_categories es [] 400, message = "No hay nada"
    :return:
    """
    categories = get_all_categories()
    status_code = HTTPStatus.OK
    if categories:
        RESPONSE_BODY["message"] = "OK. Categories List"
        RESPONSE_BODY["data"] = categories
    else:
        RESPONSE_BODY["message"] = "OK. No categories found"
        RESPONSE_BODY["data"] = categories
        status_code = HTTPStatus.NOT_FOUND

    my_info = {"categories": categories, "status_code": status_code}

    return render_template('categories.html', my_info=my_info)


@products.route('/category/<int:id>')
def get_category_products(id):
    products = get_category_products_by_id(id)
    RESPONSE_BODY["data"] = products

    my_info = {"products": products}
    return render_template('category.html', my_info=my_info)


@products.route('/add-category', methods=['POST'])
@login_required
def create_category():
    """
    Agrega categoria a la base de datos
    :return:
    """
    RESPONSE_BODY["message"] = "Method not allowed"
    status_code = HTTPStatus.METHOD_NOT_ALLOWED
    if request.method == "POST":
        data = request.json
        category = create_new_category(data["name"])
        RESPONSE_BODY["message"] = "OK. Category created!"
        RESPONSE_BODY["data"] = category
        status_code = HTTPStatus.CREATED

    return RESPONSE_BODY, status_code


@products.route('/')
def get_products():
    products_obj = get_all_products()

    RESPONSE_BODY["data"] = products_obj
    RESPONSE_BODY["message"] = "Products list"

    return RESPONSE_BODY, 200


@products.route('/product/<int:id>', methods=['GET', 'POST'])
def get_product(id):
    '''
    GET method = renderiza el template de producto
    POST method = agrega el producto a la orden, si no hay orden se crea una
    '''
    if request.method == "POST":

        quantity = int(request.form.get("quantity"))

        active_order = get_active_order(current_user)

        if active_order is None:
            create_order(current_user.id)
            active_order = get_active_order(current_user)

        if add_item_order(active_order.id, id, quantity):
            # Mensaje
            flash("Producto Agregado", 'success')
        else:
            flash("Error al Agregar producto", 'error')

        return redirect(url_for('products.get_product', id=id))

    if request.method == "GET":
        product = get_product_by_id(id)
        RESPONSE_BODY["data"] = product
        my_info = {"product": product}

    return render_template('product.html', my_info=my_info)


@products.route('/product-stock/<int:id>')
def get_product_stock(product_id):
    pass


@products.route('/need-restock')
@login_required
def get_products_that_need_restock():
    pass


@products.route('/register-product-stock/<int:id>', methods=['PUT', 'POST'])
@login_required
def register_product_refund_in_stock(id):

    # TODO Complete this view to update stock for product when a register for
    # this products exists. If not create the new register in DB

    status_code = HTTPStatus.CREATED
    if request.method == "PUT":
        data = request.json
        stock = add_stock(id, data["quantity"])
        RESPONSE_BODY["message"] = \
            "Stock for this product were updated successfully!"
        status_code = HTTPStatus.OK
    elif request.method == "POST":
        data = request.json
        stock = add_stock(id, data["quantity"])
        RESPONSE_BODY["message"] = \
            "Stock for this product were created successfully!"
        RESPONSE_BODY["data"] = stock
        status_code = HTTPStatus.CREATED
    else:
        RESPONSE_BODY["message"] = "Method not Allowed"
        status_code = HTTPStatus.METHOD_NOT_ALLOWED
    return RESPONSE_BODY, status_code


@products.route('/create-category-form', methods=['GET', 'POST'])
@login_required
def create_category_form():
    form_category = CreateCategoryForm()
    if request.method == 'POST' and form_category.validate():
        create_new_category(name=form_category.name.data)
        return redirect(url_for('products.category_success'))

    return render_template('create_category_form.html', form=form_category)


@products.route('/create-category-form-old', methods=['GET', 'POST'])
@login_required
def create_category_form_old():
    if request.method == 'POST':
        category = create_new_category(request.form["name"])
        RESPONSE_BODY["message"] = "Se agrego la categoria {} con \
            exito".format(request.form["name"])
        RESPONSE_BODY["data"] = category
        status_code = HTTPStatus.CREATED
        return RESPONSE_BODY, status_code
    return render_template("create_category_form_old.html")


@products.route('/category_success')
@login_required
def category_success():
    return render_template('category_success.html')


@products.route('/create-product-form', methods=['GET', 'POST'])
@login_required
def create_product_form():
    form_product = CreateProductForm()
    if request.method == 'POST' and form_product.validate():
        if form_product.refundable.data == "1":
            form_product.refundable.data = True
        else:
            form_product.refundable.data = False
        create_new_product(name=form_product.name.data,
                           price=form_product.price.data,
                           weight=form_product.weight.data,
                           description=form_product.description.data,
                           refundable=form_product.refundable.data,
                           category_id=form_product.category_id.data,
                           image=form_product.image.data)
        return redirect(url_for('products.product_success'))

    return render_template('create_product_form.html', form=form_product)


@products.route('/create-product-form-old', methods=['GET', 'POST'])
@login_required
def create_product_form_old():
    if request.method == 'POST':
        product = create_new_product(request.form["name"],
                                     request.form["price"],
                                     request.form["weight"],
                                     request.form["description"],
                                     request.form["refundable"],
                                     request.form["category_id"],
                                     request.form["image"])
        RESPONSE_BODY["message"] = "Se agrego el producto {} con \
            exito".format(request.form["name"])
        RESPONSE_BODY["data"] = product
        status_code = HTTPStatus.CREATED
        return RESPONSE_BODY, status_code
    return redirect(url_for('admin.add_product'))


@products.route('/product_success')
@login_required
def product_success():
    return render_template('product_success.html')


'''------Vistas agregadas------'''


@products.route('/add-product', methods=['POST'])
@login_required
def create_product():
    """
    Agregar producto a la base de datos
    :return:
    """
    RESPONSE_BODY["message"] = "Method not allowed"
    status_code = HTTPStatus.METHOD_NOT_ALLOWED
    if request.method == "POST":
        data = request.json
        product = create_new_product(data["name"], data["price"],
                                     data["weight"], data["description"],
                                     data["refundable"], data["category_id"])
        RESPONSE_BODY["message"] = "OK. Product created!"
        RESPONSE_BODY["data"] = product
        status_code = HTTPStatus.CREATED

    return RESPONSE_BODY, status_code


@products.route('/show-catalog', methods=['GET'])
def show_products_catalog():
    products = get_all_products()
    my_info = {"products": products, "pygroup": "PyGroup 01", "Jeison": 9105}
    return render_template('catalog.html', my_info=my_info)
    # Consultar la BD y extraer todos los productos disponibles
    # Almacenar la informacion en una variable de contexto
    # Renderizar la plantilla que tengamos en HTML e insertar
    # los datos de nuestra variable de contexto

Seminario de Ing Soft/Proyecto/Codigo/app/templates/add_product.html
{% extends "base_admin.html" %}

{% block panel %}

<article class="tile is-child ">
    <div class="columns is-mobile has-text-centered">
        <div class="tag is-medium column is-half is-offset-one-quarter is-warning p-4">
            <h4><strong>Agregar Producto</strong></h4>
        </div>
    </div>
    <div class="box is-offset-one-quarter is-half pr-5 pl-5 ">
        <form method="POST" action="{{ url_for('admin.add_product') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            
            <label for="name">Nombre:</label><br>
            <input class="input" type="text" id="name" name="name" placeholder="Nombre">

            <label for="precio">Precio:</label><br>
            <input class="input" type="number" id="price" name="price" placeholder="Precio">

            <label for="weight">Peso:</label><br>
            <input class="input" type="number" id="weight" name="weight" step="0.01" min="0" max="50" placeholder="Peso">

            <label for="description">Descripcion:</label><br>
            <input class="input" type="text" id="description" name="description" placeholder="Descipcion">
            
            <label for="refundable">Reembolsable:</label><br>
            <div class="box notification">
                <div class="form-check">
                    <input type="radio" name="refundable" id="opcion1" value="1"> Si <br>
                </div>
                <div class="form-check">
                    <input type="radio" name="refundable" id="opcion2" value="0"> No <br>
                    </label>
                </div>
            </div>

            <label for="category_id">Categoria ID:</label><br>
            <div class="select is-primary is-fullwidth">
                <select id="category" name="category">
                    {% for category in basics.categories %}
                    <option>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <label for="description">Imagen:</label><br>
            <input class="input" type="text" id="image" name="image" placeholder="Url Imagen">
            
            <button class="button is-success m-2">Agregar Producto</button>
        </form>
    </div>
</article>


{% endblock %}

Seminario de Ing Soft/Proyecto/Codigo/app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pygroup Shop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles_catalog.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4148c826b4.js" crossorigin="anonymous"></script>
</head>

<body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container">

        <div class="navbar-brand">
          <a class="navbar-item" href="{{ url_for('index') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}" width="112" height="28">
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-start">
            <a href="{{ url_for('index') }}" class="navbar-item">
            Inicio
            </a>
            
            <div class="navbar-item has-dropdown is-hoverable">
              <a href="{{ url_for('products.get_categories') }}" class="navbar-link">
              Categorias
              </a>

              <div class="navbar-dropdown">
                {% for category in basics.categories %}
                <a href="{{ url_for('products.get_category_products', id=category.id) }}" class="navbar-item">
                {{ category.name }}
                </a>
                {% endfor %}
              </div>
            </div>
    
        </div>

        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end"></div>

                {% if current_user.is_authenticated %}

                <div class="navbar-item has-dropdown is-hoverable">

                  <a class="navbar-link">
                    <span class="icon-text">
                      <span class="icon">
                        <i class="fas fa-user"></i>
                      </span>
                      <span>Hola<strong>&nbsp;{{ current_user.first_name }}</strong></span>
                    </span>
                  </a>
          
                  <div class="navbar-dropdown">
                      <a href="{{ url_for('order.show_shop_cart') }}" class="navbar-item">
                        Carrito
                      </a>
                      <a href="{{ url_for('admin.add_product') }}" class="navbar-item">
                        Administracion
                      </a>
                      <a class="navbar-item">
                        Medio de pago
                      </a>
                      <hr class="navbar-divider">
                      <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                        <span class="icon">
                          <i class="fas fa-times-circle"> </i>
                        </span>
                      <span>Salir</span>
                      </a>
                  </div>
                </div>

                {% else %}

                <a class="button is-warning" href="{{ url_for('auth.login') }}" class="navbar-item">
                  <span class="icon">
                    <i class="fas fa-sign-in-alt"></i>
                  </span>
                  <span>Login</span>
                </a>
                <a class="button is-light" href="{{ url_for('auth.signup') }}" class="navbar-item">
                  <span class="icon">
                    <i class="fas fa-user-plus"></i>
                  </span>
                  <span>Sign Up</span>
                </a>

                {% endif %}
            </div>
        </div>
      </div>
    </nav>
 
    {% block content %}
    {% endblock %}

    {% block home %}
    {% endblock %}

    <footer class="bg-primary text-white text-center notification text-lg-start container">
        <!-- Grid container -->
        <div class="container p-4">
          <!--Grid row-->
          <div class="row">
            <!--Grid column-->
            <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
              <h5 class="text-uppercase">Tienda Virtual</h5>
      
              <p>
                Proyecto para el grupo de trabajo Pygroup Web Edition del Capitulo de ACM
                haciendo uso de Python junto!
              </p>
            </div>
            <!--Grid column-->
      
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase">Links</h5>
      
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#!" class="text-white">Link 1</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 2</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 3</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 4</a>
                </li>
              </ul>
            </div>
            <!--Grid column-->
      
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-0">Links</h5>
      
              <ul class="list-unstyled">
                <li>
                  <a href="#!" class="text-white">Link 1</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 2</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 3</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 4</a>
                </li>
              </ul>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
          © 2021 Copyright:
          <a class="text-white">Jeison Jara</a>
        </div>
        <!-- Copyright -->
    </footer>
</body>

</html>

Seminario de Ing Soft/Proyecto/Codigo/app/templates/base_admin.html
{% extends "base.html" %}

{% block content %}

<section class="hero is-fullheight-with-navbar">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-vertical is-3">
                <div class="tile is-parent">
                    <article class="tile is-child ">

                        <div class="col-sm-12 tag is-info is-large has-text-centered">
                            <h3>MENU</h3>
                        </div>

                        <div class="content box">
                              
                            <div class="tile is-ancestor box">
                                <aside class="menu">
                                    <ul class="menu-list text-center">
                                        <a class="button is-link is-outlined m-1" href="{{ url_for('admin.add_product') }}">Agregar Producto</a>
                                        <a class="button is-link is-outlined m-1">Agregar Categoria</a>
                                        <a class="button is-link is-outlined m-1">Stock</a>
                                      </ul>
                                </aside>
                            </div>
                            
                        </div>
                    </article>
                </div>
            </div>
            <!--Subtotal-->
            <div class="tile is-parent is-vertical">

                <article class="tile is-child ">
                     
                    <div class="col-sm-12 tag is-info is-large has-text-centered">
                        <h3>ADMINISTRACIÓN</h3>
                    </div>

                    <div class="content box">
                         <!--Contenido-->
                         {% block panel %}
                         {% endblock %}
                    </div>

                </article>

            </div>
        </div>

    </div>
</section>

{% endblock %}

Seminario de Ing Soft/Proyecto/Codigo/app/templates/create_category_form.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>Crear Categoria</title>
    </head>
</html>
<body>
    <form method="POST" action="/products/create-category-form">
        {{ form.csrf_token }}
        {{ form.name.label }} {{ form.name(size=20) }}
        <input type="submit" value="Ir">
    </form>
</body>

Seminario de Ing Soft/Proyecto/Codigo/app/templates/index.html
{% extends "base.html" %}

{% block home %}
    <section class="hero is-fullheight-with-navbar">
        <div class="container">

            <!-- Banner -->
            <div class="row">
                <div class="col-sm-12">
                    <img src="{{ url_for('static', filename='images/banner.png') }}" class="img-fluid" alt="Responsive image">
                </div>
            </div>
            <div class="col-sm-12 tag"></div>
            <!--   Ultimos Productos   -->

            <div class="col-sm-12 tag is-link is-large has-text-centered">
                <h3>Productos Recientes</h3>
            </div>
            <div class="row">
                {% for product in my_info.products%}
                <div class="col-sm-4 col-lg-3">
                    <a href="{{ url_for('products.get_product', id=product.id) }}" class="text-decoration-none text-muted">
                        <div class="producto">
                            <div class="row titulo">
                                <div class="col-12">
                                    <h4> {{ product.name }} </h4>
                                </div>
                            </div>
                            <div class="row img-producto">
                                <div class="col-12">
                                    <img src="{{ product.image }}" alt="Imagen Producto" width="120" height="120">
                                </div>
                            </div>
                            <div class="row precio">
                                <div class="col-12">
                                    <span {% if product.price < 100000 %} style="color: red" {% else %} style="color: blue" {% endif %}>{{ "$ {:,.2f}".format(product.price) }}</span></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <p style="font-weight: bold;"> Descripción:</p><p class="descripcion"> {{ product.description}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {% if product.refundable %}
                                    <h6 style="color: rgb(1, 153, 1);">¡Reembolsable!</h6>
                                    {% else %}
                                    <h6 style="color: rgb(183, 1, 1);">Lo sentimos. ¡No reembolsable!</h6>
                                    {% endif %}
                                </div>
                            </div>  
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            <!--    Categorias Aleatorias   -->

            <div class="col-sm-12 tag is-primary is-large has-text-centered">
                <h3>Categorias Recomendadas</h3>
            </div>
            <div class="row">
                {% for category in my_info.random_cat %}
                    <div class="col-sm-4 col-lg-3">
                        <a href="{{ url_for('products.get_category_products', id=category.id) }}" class="text-decoration-none text-muted">
                            <div class="producto">
                                <div class="row titulo">
                                    <div class="col-12">
                                        <h4> {{ category.name }} </h4>
                                    </div>
                                </div>
                                <div class="row img-producto">
                                    <div class="col-12">
                                        <img src="{{ category.image }}" alt="Imagen Categoria" width="120" height="120">
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

Seminario de Ing Soft/Proyecto/Codigo/app/templates/product_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Producto creado exitosamente!</title>
</head>
<body>
Producto creado exitosamente!
</body>
</html>